language: rust

matrix:
  include:
    - os: linux
      rust: stable
      sudo: true
      CXX: gcc-7
      CC: gcc-7
    - os: linux
      rust: beta
      sudo: true
      CXX: gcc-7
      CC: gcc-7
    - os: linux
      rust: nightly
      sudo: true
      CXX: gcc-7
      CC: gcc-7
    - os: linux
      rust: 1.10.0
    - os: osx
      osx_image: xcode9.4
      env:
        - MACOSX_DEPLOYMENT_TARGET=10.13
      rust: stable
      sudo: true
    - os: windows
      rust: stable

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ] ; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ $TRAVIS_OS_NAME == "linux" ] ; then sudo apt-get -qq update -y; fi
  - if [ $TRAVIS_OS_NAME == "linux" ] ; then sudo apt-get -qq install g++-7 -y; fi
  - if [ $TRAVIS_OS_NAME == "osx" ] ; then  brew install gcc@7 || brew link --overwrite gcc@7; fi

script:
  - export RUST_BACKTRACE=1
  - export RUST_TEST_THREADS=1
  - cargo build --manifest-path vcpkg/Cargo.toml --verbose
  - if [ $TRAVIS_RUST_VERSION != "1.10.0" ] ; then cargo test --manifest-path vcpkg/Cargo.toml --verbose; fi
  - git clone https://github.com/Microsoft/vcpkg.git vcp
  - if [ $TRAVIS_OS_NAME == "windows" ] ; then  vcp/bootstrap-vcpkg.bat; else vcp/bootstrap-vcpkg.sh; fi
#  - if [ $TRAVIS_RUST_VERSION != "1.10.0" ] ; then systests/run.sh; fi
  # turns out harfbuzz does not work on vcpkg/linux at this point
#  - if [ $TRAVIS_RUST_VERSION != "1.10.0" ] ; then tests/run.sh; fi
  - if [ $TRAVIS_OS_NAME == "osx" ] ; then tests/run.sh; fi
